### ISSUE TITLE
Broken method call

### ISSUE THREAD

**Issue by MarkusFreitag** [thomas-krenn/TKperf#17]
There is a broken method call inside of `SsdTPTest` in [line 561](https://github.com/thomas-krenn/TKperf/blob/master/src/perfTest/DeviceTests.py#L561) . The method `setReachStdyState` is part of the `StdyState` object instead of the `SsdTPTest` itself. Replacing the mentioned line with the following one should fix this bug.
```python
self.getStdyState().setReachStdyState(False)
```

**Comment by gschoenberger** [comment]
That's correct!
Is fixed by commit c6e614339229820ea8c5995f5c85593df170e5ef
