### ISSUE TITLE
Adding IO Depth to command line?

### ISSUE THREAD

**Issue by slic14** [thomas-krenn/TKperf#20]
Is there a command line option to add IO depth?  I need to incorporate various size IODs to my drive analysis.

**Comment by gschoenberger** [comment]
$ tkperf -h
usage: tkperf [-h] [-v] [-d] [-q] [-nj NUMJOBS] **[-iod IODEPTH]** [-i {sas}]
              [-xml] [-rfb] [-dsc DESC_FILE] [-c CONFIG] [-ft]
              [-fm FEATURE_MATRIX] [-hddt {iops,tp}]
              [-ssdt {iops,lat,tp,writesat}] [-m MAIL] [-s SMTP]
              [-g GEN_REPORT]
              {hdd,ssd,raid} testname device

**Comment by slic14** [comment]
Thanks is there a way to specify multiple IO depths per run?

**Comment by gschoenberger** [comment]
No that's not possible. You have to do a run, each per IO depth.
