### ISSUE TITLE
Tkperf is running in background.

### ISSUE THREAD

**Issue by sam201709** [thomas-krenn/TKperf#21]
The Tkperf is running in background when close the terminal. 
reopen the terminal and  use "top" cmd check, the process 'fio' is running.
Why the process is running? 
And how to do ?  the Tkperf can close when close the terminal?

**Comment by gschoenberger** [comment]
Can you post the terminal command line, how you are starting tkperf?
If you need some instructions you can take a look at the Thomas-Krenn Wiki:
https://www.thomas-krenn.com/en/wiki/TKperf

**Comment by gschoenberger** [comment]
I am closing this issue, pleas open a new one if you have any further questions.
