### ISSUE TITLE
New release v2.2?

### ISSUE THREAD

**Issue by mika** [thomas-krenn/TKperf#24]
Hi,

any chance we might see a new release (v2.2)? There have been 28 commits since the latest stable version 2.1 which dates back to 2015, would be nice to get the changes since then into a new release. :)

Thanks for TKPerf!

**Comment by gschoenberger** [comment]
Yes, that's a good idea!
I will take a look at it, hopefully releasing next week,
THX Georg

**Comment by gschoenberger** [comment]
I have added version 2.2 with commit 9ebc8e169f84ccb6a6a57ef375e59ceb7a3a3e7b
THX for using TKperf!
