### ISSUE TITLE
Extend TKperf to test SD cards, Compact Flash cards and USB sticks

### ISSUE THREAD

**Issue by chris-iot** [thomas-krenn/TKperf#28]
My collegues and i at work use TKperf to test all kinds of storage devices before we release them for our products. TKperf works very well for SATA SSDs, NVMe disks and HDDs. But we also want to test SD and compact flash cards as well as USB sticks.

The idea is to add the following new interface parameters to TKperf:
- usb
- sdcard
- compactflash

Compact flash cards are attached to SATA via an active SATA to CF Adapter. For SD cards we have an adapter to fit into a Compact Flash card socket. First tests showed that with this combination the difference to SATA SSDs is not that big, just the secure erase has some issues...

If the secure erase via hdparm does not work (by try and error) it would be nice to fall back to e.g. blkdiscard or other specialized erase tools for SD cards, CF cards and USB sticks. An alternative approach is to check hdparm's info output `(hdparm -I`) if the security features are available. If they are hdparm can do the erase, if they are not alternative tools are used.

If there is no erase method left, TKperf shall continue anyway but indicate this with a warning or something similar in the log, so that there is a chance to find such things.

The big plus of adding new interface parameters is that there is a clear separation of things to do if xyz goes wrong. Otherwise the code for the SATA SSD will most likely get messed up with try/except things for this feature.

USB to SD and USB to CF adapters are out of our scope, so it is not a big deal if these combinations do not work (USB to X adapters are always a bit special...).

My collegues and i already discussed this enhancement with @gschoenberger in todays meeting, so he knows the details and constraints.

**Comment by gschoenberger** [comment]
Starting with commit 5486d3f388a5d8585ae42805e5a9d0c951978fc9 -> collecting infos about an usb device with udevadm and blockdev. Still need to test if these commands can be applied to sdcards and compactflash cards too...

**Comment by gschoenberger** [comment]
@chris-iot I saw you mentioned errors with blkdiscard in your pull request's comments.
For interfaces compactflash, sdcard and usb:

- Should we check if security feature is there, and then just skip if not?
- Should we add blkdiscard if security feature is not present?
- Or should we try to run secure erase, and if it fails got further on?

**Comment by gschoenberger** [comment]
Just in case: before starting with the secure erase method, we could check if the device supports it:
`sudo hdparm -I /dev/sda | grep "supported: enhanced erase"`
If not we could go on, with a  warning in the log file, or try to run blkdiscard.

**Comment by gschoenberger** [comment]
blkdiscard works fine for SSDs and newer sdcards/compact flash cards. One might try different adapters as they must pipe through the commands to the device

**Comment by gschoenberger** [comment]
This is a log entry from a compactflash card supporting hdparm to fetch device information, but no enhanced erase with hdparm. blkdiscard is not supported -> a log entry is entered but the test continues...
> 20181107 15:06 root     INFO     # Testing device: 	Model Number:       SDCFXPS-032G                            
> 	Serial Number:      PAZ050518110100
> 	Firmware Revision:  HDX9.03
> 	device size with M = 1000*1000:       32019 MBytes (32 GB)
> 	write-caching =  0 (off)
> Device Interface: compactflash
> 20181107 15:06 root     INFO     # Sleeping for 5 seconds...
> 20181107 15:06 root     INFO     # Trying to run Secure Erase for device: /dev/sdg
> 20181107 15:06 root     INFO     # Sleeping for 10 seconds...
> 20181107 15:07 root     INFO     # Checking for Enhanced Secure Erase with hdparm
> 20181107 15:07 root     INFO     # Running command: hdparm -I /dev/sdg | grep -q "supported: enhanced erase"
> 20181107 15:07 root     WARNING  # Enhanced Secure Erase NOT supported by device /dev/sdg
> 20181107 15:07 root     INFO     # Trying to discard all blocks with blkdiscard.
> 20181107 15:07 root     WARNING  # blkdiscard returned an error: blkdiscard: /dev/sdg: BLKDISCARD ioctl failed: Operation not supported
> 
> 20181107 15:07 root     WARNING  # Neither Secure Erase nor blkdiscard supported by device: /dev/sdg
> 20181107 15:07 root     WARNING  # Continuing tests without running Secure Erase/blkdiscard
>
