### ISSUE TITLE
DSM/TRIM via blkdiscard instead of ATA Secure Erase?

### ISSUE THREAD

**Issue by jtru** [thomas-krenn/TKperf#3]
Would patches against TKperf, that replace Secure Erase via `hdparm` (probelamtic due to the "Frozen" security feature set of most drives and HBAs) by `blkdiscard`, be considered for inclusion? They should have the same effect as far as NAND- and controller-performance go.

Also, it would enable TKperf to be benchmark partitions (which is relevant for SSDs that do not support HPA, yet the user might want to over-provision the usable space), instead of just whole disks.

**Comment by gschoenberger** [comment]
For sure we take a look at it! Please hand in patches or pull requests,

all the best, Georg

**Comment by gschoenberger** [comment]
Resolved by 3cd8d91f23fc09cc60e0987cda90096071bc97fc
