### ISSUE TITLE
Adding RAID drive fails

### ISSUE THREAD

**Issue by cmonty14** [thomas-krenn/TKperf#30]
Hi,
my understanding of running TKperf against a RAID drive is that after the first run the virtual drive will be deleted and recreated.
First, can you explain why the virtual drive is deleted and then recreated?
Second, the recreation fails when using `storcli` fails using this syntax: 
`/usr/local/bin/storcli /c0 add vd type=r0 drives=35:11 nora wt strip=strip=256`

This is the relevant log section:
```
20190113 13:29 root     INFO     # Finished workload independent preconditioning
20190113 13:29 root     INFO     # Creating raid device /dev/sdd after workload independet preconditioning!
20190113 13:29 root     INFO     # Checking for virtual drive 0/2
20190113 13:29 root     INFO     # Found raid device /dev/sdd, deleting it!
20190113 13:29 root     INFO     # Deleting raid device VD 2
20190113 13:29 root     INFO     # Creating raid device with storcli
20190113 13:29 root     INFO     # Command line: /usr/local/bin/storcli /c0 add vd type=r0 drives=35:11 nora wt strip=strip=256
20190113 13:29 root     INFO     # Got the following VDs:
```

**Comment by gschoenberger** [comment]
THX for the issue.
Should be fixed with b2e645068bca6e297115d18f9f34be2e51497b90

Cheers, Georg
