### ISSUE TITLE
StdyState.py:80 FutureWarning: `rcond` parameter

### ISSUE THREAD

**Issue by lexxua** [thomas-krenn/TKperf#31]
Hi, guys thanks for the nice software. I have the following warning:
/usr/local/lib/python2.7/dist-packages/perfTest/StdyState.py:80: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  k, d = np.linalg.lstsq(A, y)[0]

Thanks.

**Comment by gschoenberger** [comment]
I think we should stick to the old behavior  and pass rcond=-1
Can you test commit a2e71ca1edc24df888959046622fec805be08968 ?

**Comment by lexxua** [comment]
Hi @gschoenberger, thanks for patch so far no issues at all.
