### ISSUE TITLE
Can this software be used on Windows?

### ISSUE THREAD

**Issue by lijin132** [thomas-krenn/TKperf#32]
I'm really excited to see this software you wrote on GitHub. I have recently been tortured by SSS-PTS. So thank you very much.

Another question, is this based on Python 2?

**Comment by gschoenberger** [comment]
Yes this is based on Python 2.
On Windows TKperf cannot be run as it uses Linux low-level tools to manage devices (lsblk, hdparm etc.)

Cheers, Georg

**Comment by lijin132** [comment]
it's only run on ubuntu?
