### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by onitake** [thomas-krenn/TKperf#36]
With Python 2 finally [being EOL](https://www.python.org/downloads/release/python-2718/), it's time to ensure full Python 3 compatibility or even require Python 3. You may also consider joining the Python 3 alliance: https://python3statement.org/

Making TKperf compatible with Python 3 will require some conversion work. I ran all files through the `2to3` tool, and the result looked reasonable on a quick glance. I was able to run TKperf with one additional change, but haven't tested a full benchmark yet.

The dependency lists in the README should also be updated. Many of the dependencies are no longer available for Python 2 in recent Debian/Ubuntu versions, but they can be adapted for Python 3 easily.

**Comment by gschoenberger** [comment]
THX for the pool requests! I hope I can review and merge them during the next 3 weeks.
All the best, Georg

**Comment by Velociraptor85** [comment]
* https://stackoverflow.com/a/37501756/9484904 adapt the `subprocess.Popen([` commands accordingly
* change following line to `stdout.split(`
```
File "/usr/local/lib/python3.8/dist-packages/perfTest/Devices.py", line 693, in secureErase
    output_line = list([_f for _f in stdout.decode().split('\n') if _f])
AttributeError: 'str' object has no attribute 'decode'
```

currently testing on my NVMe SSDs will report back if I find any issues with proposed solution

**Comment by onitake** [comment]
> currently testing on my NVMe SSDs will report back if I find any issues with proposed solution

Please do, I'll adapt the PR accordingly. Ideally, please post a patch into the discussion for #37 .

**Comment by gschoenberger** [comment]
I think I can invest also some time an then make an new TKperf release.
Please let me know when you think your code base is somehow "ready" and I will merge your pull request.
Afterwards I can do some tests and make a review...

**Comment by Velociraptor85** [comment]
just came across this open issue ^^ I reported back in the [PR](https://github.com/thomas-krenn/TKperf/pull/37#issuecomment-826962438) but forget to confirm here
