### ISSUE TITLE
Add configuration option for MegaRAID write through or write back

### ISSUE THREAD

**Issue by tk-wfischer** [thomas-krenn/TKperf#6]
Currently for tests of MegaRAID devices the write through mode is only used and hard-coded in TKperf.

To support also tests of devices with write back, add an configuration to choose the desired mode ("write through" or "write back") for a test.

**Comment by gschoenberger** [comment]
Can you test commit ab9992c7a77cba4f8ffc9dca81ccc7d59b01fa61 ?
- Georg

**Comment by tk-wfischer** [comment]
Thanks for your commit and for your help :-) I've adjusted the option a little bit, to enable the setting of wt, wb, awb and created a branch for that (see commit 05b7700161b6fc199d8f58a8a25981dad3f89ef8 and 63e43a93abdcd617c848538d49da4bfde1b0d158).

I'll test this, and if it works, I'll remove the lines that I've commented and merge the code into master.

**Comment by tk-wfischer** [comment]
I've fixed a bug in calling the super function (9604ee25742edefbcd0d80a5a5e5209711f9833b) and removed the commented old code (14bdb18dd802204cbefc6a7a187309c8f2ee438b).

I've opened a pull request to merge the code https://github.com/thomas-krenn/TKperf/pull/10 and so I hereby close this issue.
