### ISSUE TITLE
Add date and time to log entries

### ISSUE THREAD

**Issue by tk-wfischer** [thomas-krenn/TKperf#7]
Add date and time to all log entries. This allows to analyze the runtimes of the different test steps.

**Comment by gschoenberger** [comment]
Can you test commit c847f8f54f55e1922471474666ed5d1c64794c3e ?

-Georg

**Comment by tk-wfischer** [comment]
Thank you Georg for your commit.

This works fine as you can see in the log of my currently running test:

>[...]
>20170110 10:33 root     INFO     #IOPS: 12864
>20170110 10:33 root     INFO     #Tot Write IO: 3087700
>20170110 10:33 root     INFO     #Latencies: [204.0, 58870.0, 2485.147092]
>20170110 10:33 root     INFO     ######
>20170110 10:33 root     INFO     #################
>20170110 10:33 root     INFO     Round nr. 344
>20170110 10:33 root     INFO     ['/usr/bin/fio', '--rw=randwrite', '--name=MR9361-R5-4-AWB', '--numjobs=2', '--direct=1', '--filename=/dev/sdb', '--bs=4k', '--ioengine=libaio', '--runtime=60', '--iodepth=16', '--minimal', '--time_based', '--group_reporting']
>[...]

So I'll close this issue now :-)
