### ISSUE TITLE
Creating a MegaRAID R10 configuration may fail

### ISSUE THREAD

**Issue by tk-wfischer** [thomas-krenn/TKperf#9]
The current configration file format and the currently used storcli commands may fail for a R10 with the following error:
>$ sudo /usr/local/sbin/storcli /c0 add vd type=r10 drives=252:0,1,2,3,4,5,6,7 wt nora
>Controller = 0
>Status = Failure
>Description = operation not possible for current RAID level, Cannot create configuration with 1 span

According to the [StorCLI article in our wiki](https://www.thomas-krenn.com/de/wiki/StorCLI#Erstellen_eines_Virtual_Drives) it may be neccessary to add the following parameter for a R10:
>PDperArray=2

**Comment by tk-wfischer** [comment]
Adding the "pdperarray=2" parameter fixes the issue. I'll take a look at the TKperf code to fix it there.

**Comment by tk-wfischer** [comment]
Issue should be fixed with commit 81c88332f37ea782781bf51556dd42acee7060ad

I'll test it tomorrow and I'll update this issue then.

**Comment by tk-wfischer** [comment]
The code works, the branch has been merged to master (the pull request https://github.com/thomas-krenn/TKperf/pull/11 is closed).

So this issue is fixed and I hereby close it :-)

**Comment by runxsystem** [comment]
I has met a same condition , and fixed it with "pdperarray=2", but I don't know why!
我遇到了相同的情况,也是用"pdperarray=2"才没有报错的,但是不明白pdperarray代表的是什么意义!
